update readme to point to the new repository location
appropriate/docker-jetty pull request #138
Opened 2020-06-10 00:38 UTC by lachlan-roberts

2020-06-10 07:52 UTC, gregw requested changes

2020-06-10 07:52 UTC, gregw commented on README.md
> +# Repository moved to https://github.com/eclipse/jetty.docker
I think this should be a bit better than a half sentence.

By all means lead with a big headline about how the repo has moved.    But then have a paragraph about what the repo is, how it was started by appropriate and then moved to co-reside with the jetty project at eclipse.

2020-06-16 09:50 UTC, gregw approved these changes

2020-06-16 09:50 UTC, gregw commented
@md5 what do you think?

2020-06-18 10:29 UTC, gregw commented
@md5 nudge

2020-06-19 03:48 UTC, md5 approved these changes
Looks fine. Thanks for the updates

2020-06-19 03:49 UTC, md5 commented
That being said, I would also delete all the files other than the `README.md`. This repo should also be marked as archived, which I can do if necessary.

2020-06-19 10:14 UTC, gregw commented
@md5, I think we need to keep the files here until at least we have had the official images updated.  Otherwise people will follow those links and whilst the hex codes will still point to valid targets, it may be a little confusing.    So how about we merge this, then update official images and then come back here and clean up.

2020-06-19 10:15 UTC, merged

2020-06-19 14:41 UTC, md5 commented
The official image docs have generated links back to the specific SHAs used
to build the tags, so I wouldn't worry about that

On Fri, Jun 19, 2020, 3:15 AM Greg Wilkins <notifications@github.com> wrote:

> Merged #138 <https://github.com/appropriate/docker-jetty/pull/138> into
> master.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/appropriate/docker-jetty/pull/138#event-3461848502>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAASUT7PKOMMRGOWCN4PKWLRXM3ELANCNFSM4NZ4TKNA>
> .
>

2020-06-19 15:20 UTC, joakime commented
> That being said, I would also delete all the files other than the `README.md`. This repo should also be marked as archived, which I can do if necessary.

Another option ...
You can create a new orphaned git branch which has no history, isn't based on any other branch, and only has a README.md

``` shell
cd repository
cp README.md /tmp/
git checkout --orphan archived_repo
git rm -rf .
rm '.gitignore'
cp /tmp/README.md .
git add README.md
git commit -a -m "Archived Readme"
git push origin archived_repo
```

Make that new orphaned git branch the default branch in this repo (default branch is a setting in github).
Then archive the repo in github.

2020-06-19 17:47 UTC, md5 commented
I'm not sure why we would want to disconnect the history; it seems useful
to have it readily available, not in a different branch.

The reason I think it's prudent to remove the files from HEAD is to avoid
having someone think they are current, not to render them less accessible.

On Fri, Jun 19, 2020, 8:20 AM Joakim Erdfelt <notifications@github.com>
wrote:

> That being said, I would also delete all the files other than the
> README.md. This repo should also be marked as archived, which I can do if
> necessary.
>
> Another option ...
> You can create a new orphaned git branch which has no history, isn't based
> on any other branch, and only has a README.md
>
> cd repository
> cp README.md /tmp/
> git checkout --orphan archived_repo
> git rm -rf .
> rm '.gitignore'
> cp /tmp/README.md .
> git add README.md
> git commit -a -m "Archived Readme"
> git push origin archived_repo
>
> Make that new orphaned git branch the default branch in this repo (default
> branch is a setting in github).
> Then archive the repo in github.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/appropriate/docker-jetty/pull/138#issuecomment-646694119>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAASUTYWFUUKYMX6ARTRMFTRXN65FANCNFSM4NZ4TKNA>
> .
>

2020-06-19 20:08 UTC, joakime commented
The history is still present and all of the existing shas still link.
There's no deletion, no removal.
It just a branch that is blank, isn't associated with any existing branch, or any existing tag, or any existing version, and used to community to users.

When you remove files from HEAD on the active default branch you are actually changing history and making it difficult for people to look things up, troubleshoot, follow history, or even fork and do their own thing.

Think of a new orphan branch as a "placeholder" or a "blank page" to get the end result you want.
No changing of history.
Just a README.md that shows in the github UI for people that go to the main page of the archived project.

All of the valid and useful branches still exist.
All of the tags still exist.
Even the state of the previously active default branch is still exists.